# Generated by Django 5.1.1 on 2024-09-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user_details', models.TextField()),
            ],
            options={
                'db_table': 'UserDetails',
                'indexes': [models.Index(fields=['name', 'email', 'password_hash', 'profile_image', 'user_details'], name='user_details_idx')],
            },
        ),
    ]
