# Generated by Django 5.1.1 on 2024-09-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workspacedetail_workspacemembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacedetail',
            name='invitation_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workspacedetail',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacedetail',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
