# Generated by Django 5.1.1 on 2024-10-01 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userdetails_user_details_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('groupID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('groupProfileImage', models.ImageField(blank=True, null=True, upload_to='group_profile_images/')),
            ],
            options={
                'db_table': 'GroupDetails',
                'indexes': [models.Index(fields=['groupID', 'GroupName', 'description', 'groupProfileImage'], name='group_details_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(db_column='groupID', on_delete=django.db.models.deletion.CASCADE, to='api.groupdetails')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupMembers',
                'indexes': [models.Index(fields=['userID', 'groupID'], name='group_members_idx')],
            },
        ),
    ]
