# Generated by Django 5.1.1 on 2024-10-02 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_groupdetails_groupmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDetails',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('subtask_details', models.TextField()),
                ('assignor', models.ForeignKey(db_column='Assignor_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AssignmentDetails',
            },
        ),
        migrations.CreateModel(
            name='AssignmentRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=255)),
                ('assignment', models.ForeignKey(db_column='AssignmentID', on_delete=django.db.models.deletion.CASCADE, to='api.assignmentdetails')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AssignmentRoles',
            },
        ),
        migrations.CreateModel(
            name='AssignmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('submission_id', models.CharField(max_length=255)),
                ('submission_link', models.URLField()),
                ('submission_doc', models.TextField()),
                ('points_assign', models.IntegerField()),
                ('feedback_details', models.TextField()),
                ('assignment', models.ForeignKey(db_column='AssignmentID', on_delete=django.db.models.deletion.CASCADE, to='api.assignmentdetails')),
                ('reviewer', models.ForeignKey(db_column='ReviewerID', on_delete=django.db.models.deletion.CASCADE, to='api.assignmentroles')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AssignmentStatus',
            },
        ),
        migrations.AddIndex(
            model_name='assignmentdetails',
            index=models.Index(fields=['assignment_id', 'assignor', 'assignment_description', 'deadline', 'subtask_details'], name='assignment_details_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentroles',
            index=models.Index(fields=['assignment', 'user', 'role_id'], name='assignment_roles_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentstatus',
            index=models.Index(fields=['user', 'task_id', 'status', 'reviewer', 'submission_id', 'submission_link', 'submission_doc', 'assignment', 'feedback_details'], name='assignment_status_idx'),
        ),
    ]
