# Generated by Django 5.1.1 on 2024-10-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assignmentdetails_assignmentroles_assignmentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdetails',
            name='attachments',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='assignmentdetails',
            name='subtask_details',
            field=models.JSONField(default=list),
        ),
    ]
