# Generated by Django 5.1.1 on 2024-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assignmentdetails_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignmentdetails',
            name='assignment_details_idx',
        ),
        migrations.AddField(
            model_name='assignmentdetails',
            name='assignment_name',
            field=models.TextField(default='Assignment'),
        ),
        migrations.AddField(
            model_name='assignmentstatus',
            name='submission_attachments',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='assignmentstatus',
            name='feedback_details',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='assignmentdetails',
            index=models.Index(fields=['assignment_id', 'assignor', 'assignment_name', 'assignment_description', 'deadline', 'subtask_details'], name='assignment_details_idx'),
        ),
    ]
