from django.contrib import admin  # type: ignore
from django.urls import path, include  # type: ignore
from django.conf import settings  # type: ignore
from django.conf.urls.static import static  # type: ignore

from api.views import (
    AddGroupMemberView,
    AssignmentDescriptionView,
    AssignmentStatusDetailView,
    AssignmentSubmissionView,
    CompletedAssignmentsView,
    CreateAssignmentWithMembersView,
    CrossedDeadlineAssignmentsView,
    LeaderboardView,
    ListAssignmentForReviwerView,
    ListGroupsInWorkspaceView,
    ListMembersInWorkspaceView,
    ListReveiweeForAssignmentView,
    ManageAssignmentRolesView,
    OngoingAssignmentsView,
    RemoveGroupMemberView,
    RemoveMemberFromAssignmentView,
    UpdateSubtaskFeedbackView,
    UpdateSubtaskStatusView,
    UserDetailsView,
    UserRegistrationView,
    UserLoginView,
    ProfileUpdateView,
    UserWorkspacesView,
    WorkspaceCreateView,
    GenerateInvitationLinkView,
    JoinWorkspaceView,
    OAuth2Handler,
    WorkspaceListView,
    TokenRefreshView,
    WorkspaceAccessView,
    GroupCreateView
)

oauth_handler = OAuth2Handler()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/user/register/', UserRegistrationView.as_view(), name='register'),
    path('api/user/login/', UserLoginView.as_view(), name='login'),
    path('api/user/details/', UserDetailsView.as_view(), name='user-details'),
    path('api/user/update-profile/',
         ProfileUpdateView.as_view(), name='update-profile'),
    path('api/workspace/create/', WorkspaceCreateView.as_view(),
         name='create-workspace'),
    path('api/workspace/generate-invitation/<int:workspace_id>/',
         GenerateInvitationLinkView.as_view(), name='generate-invitation'),
    path('api/workspace/join/', JoinWorkspaceView.as_view(), name='join-workspace'),
    path('api/workspace/list/', WorkspaceListView.as_view(), name='list-workspaces'),
    path('api/workspace/access/<int:workspace_id>/',
         WorkspaceAccessView.as_view(), name='workspace-access'),
    path('api/user/workspaces/', UserWorkspacesView.as_view(),
         name='user_workspaces'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('oauth/authorize/', oauth_handler.authorize_user, name='authorize_user'),
    path('callback/', oauth_handler.oauth_callback, name='oauth_callback'),
    path('api/workspace/<int:workspace_id>/create-group/',
         GroupCreateView.as_view(), name='create-group'),
    path('api/group/<int:group_id>/add-member/',
         AddGroupMemberView.as_view(), name='add-group-member'),
    path('api/group/<int:group_id>/remove-member/',
         RemoveGroupMemberView.as_view(), name='remove-group-member'),
    path('api/workspace/<int:workspace_id>/create-assignment/',
         CreateAssignmentWithMembersView.as_view(), name='create-assignment'),
    path('api/assignment/<int:assignment_id>/manage-roles/',
         ManageAssignmentRolesView.as_view(), name='manage-assignment-roles'),
    path('submissions/<str:submission_id>/',
         AssignmentSubmissionView.as_view(), name='assignment-submission'),
    path('api/workspace/<int:workspace_id>/leaderboard/',
         LeaderboardView.as_view(), name='leaderboard'),
    path('api/ongoing-assignments/', OngoingAssignmentsView.as_view(),
         name='ongoing-assignments'),
    path('api/completed-assignments/', CompletedAssignmentsView.as_view(),
         name='completed-assignments'),
    path('api/crossed-deadline-assignments/',
         CrossedDeadlineAssignmentsView.as_view(), name='crossed-deadline-assignments'),
    path('assignment-status/<int:user_id>/<int:assignment_id>/',
         AssignmentStatusDetailView.as_view(), name='assignment-status-detail'),
    path('api/workspace/<int:workspace_id>/groups/',
         ListGroupsInWorkspaceView.as_view(), name='list-groups-in-workspace'),
    path('api/workspace/<int:workspace_id>/members/',
         ListMembersInWorkspaceView.as_view(), name='list-members-in-workspace'),
    path('api/assignments/remove-member/', RemoveMemberFromAssignmentView.as_view(),
         name='remove-member-from-assignment'),
    path('api/workspace/<int:workspace_id>/assignments/',
         ListAssignmentForReviwerView.as_view(), name='list-assignments-for-reviewer'),
    path('api/workspace/<int:workspace_id>/assignments/<int:assignment_id>/reviewees/',
         ListReveiweeForAssignmentView.as_view(), name='list-reviewees-for-assignment'),
    path('api/workspace/<int:workspace_id>/assignments/<int:assignment_id>/description/',
         AssignmentDescriptionView.as_view(), name='assignment-description'),
    path('api/workspace/<int:workspace_id>/assignments/<int:assignment_id>/reviewees/<int:reviewee_id>/update-status/',
         UpdateSubtaskStatusView.as_view(), name='update-subtask-status'),
    path('api/workspace/<int:workspace_id>/assignments/<int:assignment_id>/reviewees/<int:reviewee_id>/update-feedback/',
         UpdateSubtaskFeedbackView.as_view(), name='update-subtask-feedback'),
    path('workspace/<int:workspace_id>/members/',
         ListMembersInWorkspaceView.as_view(), name='list-members-in-workspace'),
    path('workspace/<int:workspace_id>/groups/',
         ListGroupsInWorkspaceView.as_view(), name='list-groups-in-workspace'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
